### ISSUE TITLE
Incorrect payload in the README.md

### ISSUE THREAD

**Issue by quenorha** [jessejamescox/kbus-daemon-installer#1]
In the README.md, there's a missing "}" character at the end, and " are missing. 
Publishing in this state causes an unexpected daemon stop.
It should look like this :
```
{
  "state":{
      "desired":{
        "controller":{
          "modules":{
            "module2":{
              "channels":{
                "channel1":{
                 "value": true
                }
              }
            }
          }
        }
      }
    }
}
```

**Comment by jessejamescox** [comment]
Thanks Quentin!  I fixed this issue in the README and also updated the bin file per your bug find.  Please let me know what other issues you discover.

**Comment by jessejamescox** [comment]
I will also look into preventing the daemon from crashing.
