### ISSUE TITLE
FW19, libffi.so.6 missing

### ISSUE THREAD

**Issue by quenorha** [jessejamescox/kbus-daemon-installer#2]
Hi Jesse,

On FW19 PFC it seems a library is missing, I get the following error :
kbus-daemon: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory

Thanks

**Comment by jessejamescox** [comment]
I just found this also this morning. This is a firmware 19 issue. I don't yet have the BSP for firmware 19 so I need to wait to update for this firmware when it's available. For now, I can only support up to 18.

**Comment by quenorha** [comment]
Ok let's wait for FW19 SDK, works fine with FW18 though.

**Comment by jessejamescox** [comment]
Finally, I have updated this with Docker, should eliminate he dependencies in firmware: https://hub.docker.com/r/jessejamescox/pfc-kbus-api
