### ISSUE TITLE
Status Message Frequency

### ISSUE THREAD

**Issue by Vincent-BePressure** [jessejamescox/kbus-daemon-installer#4]
The controller status message posts when the run/stop switch is moved, and upon powerup.  Is there a way to get that status message re-posted to MQTT more frequently?

When a new MQTT client connects, it has no way to know the status until the status changes.

**Comment by jessejamescox** [comment]
I have updated the service and converted it to cyclic publish, rather than only on change of state event.  I have built this into a Docker container as well.  See the project here: https://hub.docker.com/r/jessejamescox/pfc-kbus-api

note: the API has changed.

**Comment by Vincent-BePressure** [comment]
Any chance of getting those changes rolled into this repository? Reason being I'm using a PFC-100 which cannot run docker unless the system is on SD card, which isn't a great solution. 

Thank you!
